var shared = {
	"equations": [
		"E = m⋅g⋅h",
		"ρ = m/V",
		"F_G = m⋅g",
		"F = D⋅s",
		"p = F_N/A" ,
		"F_R = µ⋅F" ,
		"F_A = ρ⋅g⋅h" ,
		"v = Δx/Δt",
		"a = Δv/Δt",
		"v² - v₀² = 2⋅a⋅(x - x₀)",
		"y = - ½ g⋅t²",
		"v = - g⋅t²",
		"v² = - 2⋅g⋅y",
		"F = m⋅a",
		"W = F⋅s",
		"W_h = m⋅g⋅(h - h₀)",
		"W_a = ½ ⋅m⋅(v² - v₀²)",
		"W_sp = ½ ⋅D⋅(s - s₀²)",
		"W_R = F_R⋅s",
		"E_kin = ½⋅m⋅v²",
		"E_pot = m⋅g⋅h",
		"E_pot = ½⋅D⋅s²",
		"P = W/Δt",
		"P = ΔE/Δt",
		"η = P_ab/P_zu g",
		"P = m⋅v",
		"F⋅Δt = Δp",
		"m₁⋅v₁ + m₂⋅v₂ = m₁⋅u₁ + m₂⋅u₂",
		"l₂ = l₁⋅(1 + a⋅Δt)",
		"V₂ = V₁⋅(1 + γ⋅∆T)",
		"p₁⋅V₁/T₁ = p₂⋅V₂/T₂",
		"p₁⋅V₁ = p₂⋅V₂",
		"V₁/T₁ = V₂/T₂",
		"p₁/T₁ = p₂/T₂",
		"C = Q/∆T",
		"c = C/m",
		"Q = c⋅m⋅∆T",
		"I = ∆Q/∆T",
		"R = U/I",
		"G = 1/R",
		"R = ρ⋅l/A",
		"W_el = U⋅I⋅t",
		"P_el = U⋅I",
		"E = F/q",
		"U = W/q",
		"φ = W/q",
		"U = φ₁ - φ₂",
		"E = U/d",
		"D = Q/A",
		"C = Q/U",
		"W_el = ½ U²",
		"U = l⋅B⋅v",
		"L = - U_i/İ",
		"L = μ₀⋅μ_r⋅A⋅N²/l",
		"p = m⋅v = γ⋅m_o⋅v",
		"E = m⋅c²",
		"E² - c²⋅p² = E_o²",
	],
	"variables": [
		{"letter":"TODO", "unit":"s"},
		{"letter":"TODO", "unit":"min"},
		{"letter":"TODO", "unit":"h"},
		{"letter":"TODO", "unit":"g"},
		{"letter":"TODO", "unit":"kg"},
		{"letter":"TODO", "unit":"t"},
		{"letter":"TODO", "unit":"mm"},
		{"letter":"TODO", "unit":"cm"},
		{"letter":"TODO", "unit":"m"},
		{"letter":"TODO", "unit":"km"},
		{"letter":"TODO", "unit":"N"},
		{"letter":"TODO", "unit":"kN"},
		{"letter":"TODO", "unit":"W"},
		{"letter":"TODO", "unit":"kW"},
		{"letter":"TODO", "unit":"mW"},
		{"letter":"TODO", "unit":"J"},
		{"letter":"TODO", "unit":"kJ"},
		{"letter":"TODO", "unit":"mJ"},
		{"letter":"TODO", "unit":"V"},
		{"letter":"TODO", "unit":"kV"},
		{"letter":"TODO", "unit":"mV"},
		{"letter":"TODO", "unit":"A"},
		{"letter":"TODO", "unit":"kA"},
		{"letter":"TODO", "unit":"mA"},
		{"letter":"TODO", "unit":"m/s"},
		{"letter":"TODO", "unit":"km/h"},
		{"letter":"TODO", "unit":"Ws"},
		{"letter":"TODO", "unit":"kWh"},
		{"letter":"TODO", "unit":"m/s²"},
	],
};