var shared = {
	"equations": [
		"E = m⋅g⋅h",
		"ρ = m/V",
		"F_G = m⋅g",
		"F = D⋅s",
		"p = F_N/A" ,
		"F_R = µ⋅F" ,
		"F_A = ρ⋅g⋅h" ,
		"v = Δx/Δt",
		"a = Δv/Δt",
		"v² - v_0² = 2⋅a⋅(x - x_0)",
		"y(t) = - ½ g⋅t²",
		"v(t) = - g⋅t²",
		"v² = - 2⋅g⋅y",
		"F = m⋅a",
		"W = F⋅s",
		"W_h = m⋅g⋅(h - h_0)",
		"W_a = ½ ⋅m⋅(v² - v_0²)",
		"W_sp = ½ ⋅D⋅(s - s_0²)",
		"W_R = F_R⋅s",
		"E_kin = ½⋅m⋅v²",
		"E_pot = m⋅g⋅h",
		"E_pot = ½⋅D⋅s²",
		"P = W/Δt",
		"P = ΔE/Δt",
		"η = P_ab/P_zu g",
		"P = m⋅v",
		"F⋅Δt = Δp",
		"m_1⋅v_1 + m_2⋅v_2 = m_1⋅u_1 + m_2⋅u_2",
		"l_2 = l_1⋅(1 + a⋅Δt)",
		"V_2 = V_1⋅(1 + γ⋅∆T)",
		"p_1⋅V_1/T_1 = p_2⋅V_2/T_2",
		"p_1⋅V_1 = p_2⋅V_2",
		"V_1/T_1 = V_2/T_2",
		"p_1/T_1 = p_2/T_2",
		"C = Q/∆T",
		"c = C/m",
		"Q = c⋅m⋅∆T",
		"I = ∆Q/∆T",
		"R = U/I",
		"G = 1/R",
		"R = ρ⋅l/A",
		"W_el = U⋅I⋅t",
		"P_el = U⋅I",
		"E = F/q",
		"U = W/q",
		"φ = W/q",
		"U = φ_1 - φ_2",
		"E = U/d",
		"D = Q/A",
		"C = Q/U",
		"W_el = ½ U^2",
		"U = l⋅B⋅v",
		"L = - U_i/İ",
		"L = μ_0⋅μ_r⋅A⋅N^2/l",
		"p = m⋅v = γ⋅m_o⋅v",
		"E = m⋅c^2",
		"E^2 - c^2⋅p^2 = E_o^2",
	],
	"letters": [
	],
	"units": [
		"s",
		"min",
		"h",
		"g",
		"kg",
		"t",
		"mm",
		"cm",
		"m",
		"km",
		"N",
		"kN",
		"W",
		"kW",
		"mW",
		"J",
		"kJ",
		"mJ",
		"V",
		"kV",
		"mV",
		"A",
		"kA",
		"mA",
		"m/s",
		"km/h",
		"Ws",
		"kWh",
		"m/s²"
	],
};